=== `App Starters Security` Common Module

Spring Boot auto-configuration to manage the web security of the application starters.

The `spring.cloud.stream-app-starters.security.enabled` and `spring.cloud.stream-app-starters.security.csrf-enabled` can customize adapter's behavior.
Setting `spring.cloud.stream-app-starters.security.enabled = false` would completely surpass the security for the application.
For secured application setting `spring.cloud.stream-app-starters.security.csrf-enabled = false` would disable only the CSRF access.

If the security is enabled (e.g. `spring.cloud.stream-app-starters.security.enabled = true`) and the actuator dependency is on the classpath then it falls back to `ManagementWebSecurityAutoConfiguration` allowing unauthenticated access to the HealthEndpoint and InfoEndpoint.

Setting `spring.cloud.stream-app-starters.security.enabled = false` surpasses the security for the entire application.

Setting `spring.cloud.stream-app-starters.security.csrf-enabled = false` disables the CSRF.

If the user specifies their own `WebSecurityConfigurerAdapter`, this will back-off completely and the user should specify all the bits that they want to configure as part of the custom security configuration.

=== Configuration
To include app starters security management for a stream app, just include a dependency on this module.

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud.stream.app</groupId>
    <artifactId>app-starters-security-common</artifactId>
</dependency>
----

Spring Cloud Stream application starters that inherit the `core` will have this dependency included by default.

* `spring.cloud.stream-app-starters.security.enabled` - `false` surpasses the boot security.
* `spring.cloud.stream-app-starters.security.csrf-enabled` - even with spring.cloud.app-starter-stream.security.enabled set to true you can enable CQRS by setting csrf-enabled to false.
