=== `App Starters Security` Common Module

Spring Boot auto-configuration to manage the web security of the application starters.

It also provides default configuration for web security when the actuator dependency is on the classpath. By default it allows unauthenticated access to the `HealthEndpoint`, `LogFileWebEndpoint`, `InfoEndpoint` and `BindingsEndpoint`.

The `spring.cloud.stream.security.enabled` and `spring.cloud.stream.security.csrf-enabled` can customize adapter's behavior. Setting `spring.cloud.stream.security.enabled = false` would completely surpass the security for the application. For secured application setting `spring.cloud.stream.security.csrf-enabled = false` would disable only the CSRF access.

If the user specifies their own {@link WebSecurityConfigurerAdapter}, this will back-off completely and the user should specify all the bits that they want to configure as part of the custom security configuration.

=== Configuration
To include app starters security management for a stream app, just include a dependency on this module.

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud.stream.app</groupId>
    <artifactId>app-starters-security-common</artifactId>
</dependency>
----

Spring Cloud Stream application starters that inherit the `core` will have this dependency included by default.

Additional properties allow to further fine tune the security control.

* `spring.cloud.stream.security.enabled` - `false` surpasses the boot security.
* `spring.cloud.stream.security.csrf-enabled` - even with spring.cloud.stream.security.enabled set to true you can enable CQRS by setting csrf-enabled to false.
